trigger:
- main

pool:
  name: Default  # Ensure the correct pool name is specified

variables:
  system.debug: true  # Enable debug logs

steps:
- task: Checkout@1
  displayName: 'Checkout Code'

- script: |
    python3 -m venv .venv
    source .venv/bin/activate
    pip install --upgrade pip
  displayName: 'Set Up Virtual Environment'

- script: |
    source .venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    source .venv/bin/activate
    pytest
  displayName: 'Run Tests'