trigger:
- main

pool:
  name: Default

steps:
- script: |
    python3 --version
    python3 -m venv .venv
    source .venv/bin/activate
    python3 -m pip install --upgrade pip
  displayName: 'Set up Python Virtual Environment'

- script: |
    source .venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    source .venv/bin/activate
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run Tests'