trigger:
- main

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Use Python 3.x'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      python3 -m venv .venv
      source .venv/bin/activate
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
  displayName: 'Setup Python Virtual Environment and Install Dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      source .venv/bin/activate
      pip install pytest pytest-azurepipelines
      pytest
  displayName: 'Run Tests'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      deactivate
      rm -rf .venv
  displayName: 'Clean Up Virtual Environment'
  condition: always()