trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals ip-172-31-24-250

steps:
- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run tests'