trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals ip-172-31-24-250

steps:
- script: |
    python3 -m venv .venv  # Create a virtual environment
    source .venv/bin/activate  # Activate the virtual environment
    pip install --upgrade pip  # Upgrade pip
    pip install -r requirements.txt  # Install dependencies
  displayName: 'Set Up Virtual Environment and Install Dependencies'

- script: |
    source .venv/bin/activate  # Activate the virtual environment
    pip install pytest pytest-azurepipelines  # Install test dependencies
    pytest  # Run tests
  displayName: 'Run Tests'