trigger:
- main

resources:
- repo: self


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default  
      
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
    
    - script: |
        docker images --filter reference=$(Build.BuildId)
      displayName: Verify and list the new image